import type { Metadata } from "next";
import { Geist_Mono, Nanum_Gothic } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import AuthSession from "./_components/AuthSession";

const geistNanum = Nanum_Gothic({
  weight: "700",
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistNanum.variable} ${geistMono.variable} antialiased`}
      >
        <AuthSession>
          <Header />
          <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
            {children}
          </div>
          <div id="modal-root"></div>
        </AuthSession>
      </body>
    </html>
  );
}
